### ISSUE TITLE
app doesn't work in multicast mode

### ISSUE THREAD

**Issue by adbenitez** [deltachat/AndroidYggmail#17]
I setup a yggmail in my laptop and setup a hotspot then connect with my phone to the hotspot and run the yggmail apk but the two yggmail servers don't see each other, both on multicast-only mode, on the other hand running yggmail CLI inside Termux works like a charm so it is something specific to the app, in the logs I see: `failed to add peer: unknown call scheme` when there are no peers at all

**Comment by cyBerta** [comment]
fixed with https://github.com/deltachat/AndroidYggmail/pull/23 and https://github.com/deltachat/yggmail/commit/5d02272c33ea99eeff3f470a2f77010e650de24c
