### ISSUE TITLE
Fetch public peers on initial startup

### ISSUE THREAD

**Issue by cyBerta** [deltachat/AndroidYggmail#20]
Currently we preship a couple of public peers the app will initially try to connect to a public peer. Unfortunately the public peers are quite unstable and are not reachable after some time. 
To avoid the situation that no preconfigured peer is available anymore we should ensure to initially fetch the latest list.
We could add a progress / splash screen while fetching the list, so that the user is blocked to start yggmail manually before we can ensure we have the list of public peers.

**Comment by adbenitez** [comment]
addressed in #33
